// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SimpleMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250523084926_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("Dane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tekst")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Dane");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Tekst = "To jest pierwszy komentarz."
                        },
                        new
                        {
                            Id = 2,
                            Tekst = "Drugi przykładowy wpis."
                        },
                        new
                        {
                            Id = 3,
                            Tekst = "Trzeci tekst testowy."
                        });
                });

            modelBuilder.Entity("Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Loginy");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LoginName = "admin",
                            Password = "E64B78FC3BC91BCBC7DC232BA8EC59E0"
                        },
                        new
                        {
                            Id = 2,
                            LoginName = "user",
                            Password = "6EDF26F6E0BADFF12FCA32B16DB38BF2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
